Numpy is a fundamental package for scientific computing in python. It is a python library that provides a multidimensional array object and various derived objects like masked arrays or matrices and an assortment of routines for fast operation on arrays including mathematical,logical,shape manipulation,sorting,selecting,I/O,Discrete Fourier transform,basic linear algebra,statistical operations,random simulation etc.

At the core of the numpy package is going to be the n dimensional array object.(suppose for 2D image, numerical data in x and y axis and for 3D, numerical data or arrays in three axis(x,y,z)

Why there is a need to learn numpy?
## WHY Numpy ?

### 2008-2009, Data science ---> Matlab , R Language

## Data Types in Python --> List , Dictionary--> Slow
C and java were low level languages they faster but they had difficult syntax compared to python. because in c compiler is used and in python interpreter so python is relatively slower but numpy is written in C and then wrapped in python so it is faster than normal python codes with ofc easier syntax bcoz of python.low level languages are closer to hardware and high level are closer to human language,hence python is high level and c is low because language is pretty closer to hardware or CPU understandable.
Syntax--> Python --> Easy
## We needed Speed and Less Memory to work with the huge amount of data .

Numpy --> C language --> wrapped ---> Python language

## Numpy--> syntax--> Easy for beginners--> Performing Scientific Calculations ---> Creating Multi Dimensional Arrays---> Speed is faster for applying Operations ---> Less Memory

### Libraries like Scikit Learn , Tensorflow and Pytorch require input data in Numpy Arrays or Tensors .

## Numpy Arrays Vs Python Sequences

### Numpy Arrays have a fixed size at creation, unlike Python Lists which grow dynamically.
Changing the size of an ndarray array will create a new array and delete the original.

### The elements in a Numpy Array are required to be of the same data type and thus will be of the same size in memory.

### Numpy Arrays facilitate advanced Mathematical and other types of operations on large numbers
of data. Typically, such operations are executed more efficiently with less code than is
possible using Python's built-in sequences.

so basically in machine learning, we give machine an input and machine gives us output. but how does that machine gives output based on that input is because in the backend some functionalitites or mathematical functionalities keeps on working. So,we need to train our machine based on it on huge amount of data and that data must be converted into some mathematical values if original data is in image or string format so that based on that huge mathematical data our machine can perform operations and give us the desired output. machine works on mathematical data because it works on binary system(1s and 0s),electrical signals which happens through 1s and 0s. Hence, the data should be mathematical for that. So,we need to convert our input data into mathematical numbers or arrays or matrices(which are basically used for huge amount of data),and that job can be done by using libraries like numpy.

In [53]:
import numpy as np #np is the alias or object that we also created in case of oop. through creation of object we accessed all the methods and attributes inside the class similarly through object or alias that we created we can access all the functionalities or attributes inside that library.

In [54]:
#to create numpy array
numpy_array=np.array([1,2,3,4,5])


In [55]:
numpy_array #so it created a single row of elements so it is a 1-D array which is also called vector and if columns were also present then it is called 2-D array which is also called matrix. and 3D array would be called tensor.

array([1, 2, 3, 4, 5])

In [56]:
type(numpy_array) #nd means n dimensional. here it is single row so it is 1d array

numpy.ndarray

In [57]:
Twodarray=np.array([[1,2,3],[4,5,6],[7,8,9]]) #these lists inside main list are number of rows, so here there is 3 rows. and each mini list must have same dimension meaning same number of elements for the creation of numpy array. rows and columns could be as many as you like and also elements but only thing is element must be  constant in all list like if 5 numbers then 5 in every and also if there are just row and column then it is a 2d array always.

In [58]:
Twodarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
Threedarray=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) #for z=1, rows and columns are [1,2],[3,4],for z=2 and 3 same procedure. so row and colum are x and y and z if third dimension. for 3d always use 3 square brackets and for 2d two square brackets.

In [60]:
Threedarray

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## np.array() ---> creating the multidimensional arrays

## dtype parameter ---> which can help us out with deciding about the size of the data we are going to store inside our array.

In [61]:
np.array([1,2,3,4,5],dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [62]:
np.array([1,2,3,4,5],dtype=np.int64) #here integers are stored inside list with 64 bits so ofc it is going to take larger memory as compared to 34 bits. so it is upon us how can we manage efficient storage.

array([1, 2, 3, 4, 5])

In [63]:
# similarly we can have np.float64,np.float32

In [64]:
np.array([1,2,3,4,5],dtype=float) #all elements must be of same datatype in array.

array([1., 2., 3., 4., 5.])

In [65]:
np.array([1,2,3,4,5],dtype=bool) #because all are positive values hence true. 

array([ True,  True,  True,  True,  True])

## arange()---->it helps us out with providing the values over a certain range(from 0 to -1th index or range). It overcomes writing long lines of code through looping statements.

In [66]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [67]:
np.arange(5,21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [68]:
np.arange(2,21,2) #last digit in shows how many numbers to skip

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## np.reshape()---->it changes the shape of array as per our needs. like if there is a single row with 16 elements it could be modified into 4 rows and 4 columns with 4 elements in single row, so total could be 16, similarly 2 row and 8 columns would also be 16. So,multiplication of rows and columns must be equal to total size of array.

In [69]:
arange_data=np.arange(1,17)


In [70]:
arange_data.reshape(4,4) #4 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
arange_data.reshape(2,8) #2 rows and 8 columns

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [72]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [73]:
# ones function is used to store value as 1 of each element in a defined shape. It initializes the weight of neurons in the neural network architecture.
np.ones((4,4)) # here 4 rows n 4 columns are created.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
# zeros function is used to store value as 0 of each element in defined shape.
np.zeros((4,5),dtype=int)


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## random() helps us out with generating any random values between 0 and 1 in our matrix of defined shape

In [75]:
np.random.random((3,4)) #it is inside random library so two times random is being used.

array([[0.9193209 , 0.75394628, 0.85135004, 0.23290488],
       [0.76458066, 0.02486279, 0.47930901, 0.24524426],
       [0.24489031, 0.00139786, 0.99044447, 0.59254991]])

## Identity()---->It helps us out with creating a identity matrix(it is a square matrix--->rows=columns,in identity matrix diagonal values are 1 except that all 0)

In [76]:
np.identity(3) #as rows=columns, so just one parameter passed.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## if we store random numbers from 1 to 100 in variable, it takes too much time and effort and memory. so we came out with data structure to store it in a single variable that contains lots of numbers and inputs, so that by accessing it everything inside it could be accessed. In the same way, we came out with arrays and matrices that stores large data in structured format so that by accessing an array we can go through it entirely. the way in which data is stored in array like by using [],[[]],[[[]]] creates 1d,2d,3d array which is a way of storing data in different formats and for different operations and use case.

## linspace()---->it make sure that every value within the given range is going to have similar distance from each other.

In [77]:
np.linspace(-10,10,10) #(lower limit,upper limit,total elements in matrix), all values generated are of similar difference.

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## Attributes

ndim--->it stands for n dimension so it shows the dimension of current array.

In [78]:
arr=np.array([1,2,3,4,5])

In [79]:
arr.ndim #attributes are passed without () attributes are the properties just like the name itself,dimension,shape etc are the properties,just like how we did in oops.functions are passed with (),functions are the functionalities or methods.

1

shape---->provides us with the idea about the rows and column in our numpy array.

In [80]:
ary=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [81]:
ary.shape

(3, 3)

In [ ]:
ThreeDArray = np.array([[[1,2],[3,4]],[[1,2],[3,4]]]) #z axis has 2 2d plots meaning one z axis has 2 row column and other has 2 row column.

ThreeDArray.shape

(2, 2, 2)

In [23]:
ThreeDArray

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

size-->Total number of elements present inside our dataset or arrays.

In [82]:
array_elements=np.arange(5,57)

In [83]:
array_elements.size

52

itemsize--->provides the size of single element in our array in bytes.

In [84]:
np.array([[1,2],[3,4],[5,6]]).itemsize

8

In [ ]:
np.array([[1,2],[3,4],[5,6]],dtype=np.int32).itemsize #hence each element91,2,3,4etc) is of 4 bytes,so we can transform size for efficient memory usage.

4

dtype--->it gives the type of every item inside our array

In [86]:
np.array([[1,2,3],[4,5,6]]).dtype

dtype('int64')

astype()--->it will figure out the datatype of the column in dataset in pandas and it will be used in numpy for getting the datatype changed of our overall array. 

In [87]:
ar=np.arange(1,10).reshape(3,3)

In [88]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
ar.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
ar=ar.astype('float64') #this function is useful to store elements in less memory so efficient in data cleaning process.

In [92]:
ar.dtype

dtype('float64')

## Mathematical operations in numpy: It is useful so that after creating array, operations could be performed to get desired output.

scalar operations--->A scalar value operation will be done with the overall array or a numeric value(1,4 etc)

In [93]:
array=np.random.random((3,3))*100

In [95]:
np.round(array)

array([[34., 45., 42.],
       [11.,  2., 41.],
       [43., 99., 87.]])

In [96]:
array=array.astype('int32')

In [97]:
array

array([[34, 45, 42],
       [11,  1, 41],
       [42, 98, 87]], dtype=int32)

Scalar operations with matrix or array

In [ ]:
array+2 #this scalar or numeric value will be operated on each element inside the matrix

array([[ 36,  47,  44],
       [ 13,   3,  43],
       [ 44, 100,  89]], dtype=int32)

In [99]:
array-5

array([[29, 40, 37],
       [ 6, -4, 36],
       [37, 93, 82]], dtype=int32)

In [100]:
array*2

array([[ 68,  90,  84],
       [ 22,   2,  82],
       [ 84, 196, 174]], dtype=int32)

In [ ]:
array/2 #division will ultimately give us the float value

array([[17. , 22.5, 21. ],
       [ 5.5,  0.5, 20.5],
       [21. , 49. , 43.5]])

We can apply scalar operations with the array in terms of arithmetic operations and relational operations,(like >,< etc).

In [102]:
array>60

array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])

Vector Operations--->the operations will be in between the given number of matrices.

In [103]:
arr_1=np.arange(1,17).reshape(4,4)

In [104]:
arr_2=np.arange(17,33).reshape(4,4)

In [ ]:
arr_1+arr_2 #vector operations are performed between two arrays. so elements of first array operated with corresponding elements of other array.

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [106]:
arr_2-arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [107]:
arr_1*arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

# Important functions in numpy for machine learning and data science

max()---->It is used to calculate the max value inside a matrix or array
syntax is np.max(array)

In [108]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [109]:
np.max(arr_1)

np.int64(16)

axis()--->it provides the idea about any operation value inside a specific row or column or we can get a specific value rowwise or columnwise. axis=0, columnwise operation, axis=1, rowwise opertion.

In [110]:
a=np.round(np.random.random((4,4))*100).astype('int32')

In [111]:
a

array([[95, 39, 99, 33],
       [ 8, 46,  8, 88],
       [54, 59, 63, 62],
       [13,  5, 73, 92]], dtype=int32)

In [ ]:
np.max(a,axis=0) #columnwise operation

array([95, 59, 99, 92], dtype=int32)

In [ ]:
np.max(a,axis=1) #rowwise operation

array([99, 88, 63, 92], dtype=int32)

min()---->it will calculate the minimumn value from the matrix or array. syntax is np.min

In [114]:
np.min(a)

np.int32(5)

In [115]:
np.min(a,axis=1)

array([33,  8, 54,  5], dtype=int32)

In [116]:
np.min(a,axis=0)

array([ 8,  5,  8, 33], dtype=int32)

In [117]:
arr=np.arange(1,10)

In [118]:
np.max(arr)

np.int64(9)

In [119]:
np.min(arr)

np.int64(1)

sum()---->calculates the sum of all values of a given matrix. Syntax is np.sum(array)

In [120]:
a

array([[95, 39, 99, 33],
       [ 8, 46,  8, 88],
       [54, 59, 63, 62],
       [13,  5, 73, 92]], dtype=int32)

In [ ]:
np.sum(a) #sum of all elements of the given matrix

np.int64(837)

In [ ]:
np.sum(a,axis=1) #sum of values rowwise

array([266, 150, 238, 183])

In [123]:
np.sum(a,axis=0)

array([170, 149, 243, 275])

prod()---->it helps with calculating product of all values inside matrix. syntax is np.prod(array)

In [125]:
a

array([[95, 39, 99, 33],
       [ 8, 46,  8, 88],
       [54, 59, 63, 62],
       [13,  5, 73, 92]], dtype=int32)

In [126]:
np.prod(a)

np.int64(-1373597046268608512)

In [127]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.prod(arr) #it will give 9 factorial

np.int64(362880)

In [129]:
np.prod(a,axis=1)

array([12104235,   259072, 12444516,   436540])

In [130]:
np.prod(a,axis=0)

array([  533520,   529230,  3642408, 16564416])

## Statistical functions in Numpy

mean()---->syntax is np.mean(array). mean of all values inside the array or matrix.

In [131]:
np.mean(a)

np.float64(52.3125)

In [132]:
np.mean(a,axis=1)

array([66.5 , 37.5 , 59.5 , 45.75])

In [133]:
np.mean(a,axis=0)

array([42.5 , 37.25, 60.75, 68.75])

std()---->it provides the standard deviation of all values of matrix or array.

In [134]:
np.std(a)

np.float64(31.459733688478675)

median()---->to calculate median of all values in the array or matrix. syntax for median is np.median(array)

In [135]:
np.median(a)

np.float64(56.5)

var()----> it helps with calculating the variance of all values inside the array or matrix. syntax is np.var(array)

In [136]:
np.var(a)

np.float64(989.71484375)

## Trigonometric functions in numpy

sin()--->provides the sin value for the value we are going to pass inside it. np.sin()

In [137]:
np.sin(0)

np.float64(0.0)

In [138]:
np.sin(60)

np.float64(-0.3048106211022167)

In [139]:
np.tan(45)

np.float64(1.6197751905438615)

In [140]:
np.cos(12)

np.float64(0.8438539587324921)

## Dot product of matrices:
 syntax is np.dot(matrix1,matrix2)
 In dot product, the row of 1st matrix=column of 2nd matrix(elements wise,basically shape) and the column of 1st matrix=row of 2nd matrix(like 4,5=5,4). and the dot product of it will generate a matrix of 4,4


In [142]:
matrix_1=np.round(np.random.random((3,4))*100).astype('int32')

In [143]:
matrix_2=np.round(np.random.random((4,3))*100).astype('int32')

In [ ]:
matrix_1 #(3,4)

array([[76, 19, 77, 83],
       [72, 81, 62, 27],
       [16, 18, 94, 37]], dtype=int32)

In [ ]:
matrix_2 #(4,3)

array([[18, 57, 90],
       [22, 87,  5],
       [59, 14,  8],
       [68, 15, 48]], dtype=int32)

In [ ]:
np.dot(matrix_1,matrix_2) #(3,3)

array([[11973,  8308, 11535],
       [ 8572, 12424,  8677],
       [ 8746,  4349,  4058]], dtype=int32)

log()---->to calculate the log of all values of our matrix. syntax is np.log(array)

In [147]:
np.log(matrix_1)

array([[4.33073334, 2.94443898, 4.34380542, 4.41884061],
       [4.27666612, 4.39444915, 4.12713439, 3.29583687],
       [2.77258872, 2.89037176, 4.54329478, 3.61091791]])

exp()--->to calculate exponential of all values inside matrix. syntax is np.exp(array)

In [148]:
np.exp(matrix_1)

array([[1.01480039e+33, 1.78482301e+08, 2.75851345e+33, 1.11286375e+36],
       [1.85867175e+31, 1.50609731e+35, 8.43835667e+26, 5.32048241e+11],
       [8.88611052e+06, 6.56599691e+07, 6.66317622e+40, 1.17191424e+16]])

round()----> it helps us with rounding off the float values to it's nearest possible integer values. syntax is np.round(array)

In [149]:
arr=np.random.random((3,4))

In [155]:
arr

array([[0.52593584, 0.14506422, 0.09104122, 0.60517337],
       [0.69948045, 0.23050359, 0.47905121, 0.48856819],
       [0.67019988, 0.75181429, 0.81098789, 0.00373957]])

In [158]:
arr=arr*10

In [159]:
arr

array([[5.25935844, 1.45064218, 0.91041221, 6.05173374],
       [6.99480447, 2.30503591, 4.79051213, 4.88568192],
       [6.70199876, 7.5181429 , 8.10987892, 0.03739574]])

In [160]:
np.round(arr)

array([[5., 1., 1., 6.],
       [7., 2., 5., 5.],
       [7., 8., 8., 0.]])

In [161]:
'''
round() ---> 1.6 --> 2   1.3 ---> 1

ceil()  ---> 1.6 --> 2   1.3 ---> 2

floor() ---> 1.6 --> 1   1.3 ---> 1
'''

'\nround() ---> 1.6 --> 2   1.3 ---> 1\n\nceil()  ---> 1.6 --> 2   1.3 ---> 2\n\nfloor() ---> 1.6 --> 1   1.3 ---> 1\n'

ceil()---->next corresponding value--->np.ceil()

In [162]:
np.ceil(arr)

array([[6., 2., 1., 7.],
       [7., 3., 5., 5.],
       [7., 8., 9., 1.]])

floor()--->provides us with the previous value. syntax is np.floor(array)

In [163]:
np.floor(arr)

array([[5., 1., 0., 6.],
       [6., 2., 4., 4.],
       [6., 7., 8., 0.]])

Transpose()---->It calculates the transpose of the given matrix. syntax is np.transpose(array) or array.T, By transpose we mean (i,j)--->(j,i), (3,4)---->(4,3), the number of columns will become number of rows and vice versa.

In [167]:
arr=np.arange(1,13).reshape(3,4) #always use shape as per the elements inside matrix, if only 12 elements then shape would be the product of row and column, which will give value as 12, like 4,3 etc

In [168]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [169]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [170]:
np.transpose(arr)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

ravel()--->np.ravel()---->converts the nd array into 1d array.

In [171]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [172]:
arr.ndim

2

In [174]:
arr=np.ravel(arr)

In [175]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [176]:
arr.ndim

1

## Indexing and Slicing in Numpy

In [177]:
array=np.round(np.random.random((5,5))*100).astype('int32')

In [178]:
array

array([[29, 76, 46, 83, 21],
       [62, 45, 84,  3, 88],
       [43, 10, 74, 90, 49],
       [97, 81,  7, 71, 43],
       [52, 72, 14, 17, 63]], dtype=int32)

In [179]:
array_one=np.arange(1,10)

In [180]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Indexing is used to access over elements inside our matrix. quite similar to indexing in list. we use index value here also starting from 0 to -1.

In [ ]:
array_one[6] #here it is index value in square bracket.

np.int64(7)

In [182]:
array_one[-1]

np.int64(9)

In [ ]:
#in case of 2d array--->(row,column index) within square bracket, in case of 3d array--->(z,x,y) within square bracket. index values of all starting from 0.
array

array([[29, 76, 46, 83, 21],
       [62, 45, 84,  3, 88],
       [43, 10, 74, 90, 49],
       [97, 81,  7, 71, 43],
       [52, 72, 14, 17, 63]], dtype=int32)

In [184]:
array[4,4]

np.int32(63)

In [185]:
array[2,3]

np.int32(90)

In [186]:
array_3=np.arange(1,9).reshape(2,2,2)

In [ ]:
array_3 #3d arrays are combination of 2d arrays. z=1, has 1 2d array, z=2, has another and so on.

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [188]:
array_3[0,0,1]

np.int64(2)

In [189]:
array_3[0,1,0]

np.int64(3)

## Slicing--->has similar approach just like the lists[:]
2d array--->[row1:row2,col1:col2]

In [190]:
array

array([[29, 76, 46, 83, 21],
       [62, 45, 84,  3, 88],
       [43, 10, 74, 90, 49],
       [97, 81,  7, 71, 43],
       [52, 72, 14, 17, 63]], dtype=int32)

In [ ]:
array[:,2] #: is to get all values and 2 is for index of 3rd column.

array([46, 84, 74,  7, 14], dtype=int32)

In [192]:
array[0,:] #to get access over 1st row

array([29, 76, 46, 83, 21], dtype=int32)

In [ ]:
array[2:4,3:5] #here 2nd index row to 3rd index(+1th is written in the actual so to ignore it) and 3rd index column to 4th index(again +1 to ignore it)

array([[90, 49],
       [71, 43]], dtype=int32)

In [194]:
array[2:,1:4]

array([[10, 74, 90],
       [81,  7, 71],
       [72, 14, 17]], dtype=int32)

# Iterating over an array

In [195]:
array=np.arange(1,10)

In [196]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [197]:
array=np.arange(1,17).reshape(4,4)

In [198]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
for i in array: #in case of 2d array, it will be shown row by row.
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [201]:
array=np.arange(1,28).reshape(3,3,3)

In [202]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
for i in array: #in 3d array we will get all the 2d arrays inside it.
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


nditer()--->helps us out with iterting over every value in nd array. np.nditer() is the syntax.

In [204]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
for i in np.nditer(array): #here all the values of 3d array we will get, instead of just 2d arrays.
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


## stacking and splitting in array-->size of the arrays must be the same.

## stacking--> joining the array together. row by row joining in case of of hz stacking and in case of vt, column by column joining. hstack() for hz joining and vstack() for vt joining.
splitting--->we are going to split arrays in 2 arrays. horizontal split(appears vt but it is horizontal because horizontal stacking is done so in this way splitting will also be done.),same goes with vertical split


In [206]:
array_one = np.arange(1,13).reshape(3,4)

array_one

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [207]:
array_two = np.arange(13,25).reshape(3,4)
array_two

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [208]:
horizontal_array = np.hstack((array_one, array_two, array_one, array_two))
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16,  1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20,  5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24,  9, 10, 11, 12, 21, 22, 23, 24]])

In [209]:
vertical_array = np.vstack((array_one, array_two))

vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

## Horizontal split ---> np.hsplit(array, number of parts you want your array to be splitted at)

## vertical slit ---> np.vsplit(array, number of parts)

In [210]:
np.hsplit(vertical_array, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [211]:
np.vsplit(vertical_array, 2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [212]:
np.vsplit(vertical_array, 3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]